sudo: false
language: python
python:
    - '2.7'
    - '3.4'
    - '3.5'
    - 'pypy'
before_install:
    - pip install -U pip wheel setuptools
install:
    - pip install cython
    - if [ ${TRAVIS_PYTHON_VERSION} == 'pypy' ]; then travis_retry pip install cffi lxml-cffi; fi
    - pip install -r requirements.txt
script:
    true
addons:
  apt:
    packages:
    - python-libxml2
    - libtiff4-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
matrix:
  allow_failures:
    - python: pypy
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email: false
