language: python
python:
    - '2.7'
    - '3.4'
    - '3.5'
    - 'pypy'
before_install:
    - pip install cython
install:
    - pip install -r requirements.txt
script:
    true
addons:
  apt:
    packages:
    - libxml2-dev
    - libxslt-dev
    - python-dev
    - gcc
cache:
  directories:
    - $HOME/.cache/pip
